spring:
  thymeleaf:
    cache: false
    suffix: .html
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1/dbgirl?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update