spring:
  thymeleaf:
    cache: false
    suffix: .html #后缀
    check-template: true  #检查存在
    prefix: classpath:/templates/ #文件位置前缀
    servlet:
      content-type: text/html
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1/dbgirl?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /prac
