#spring:
#  ldap:
#    embedded:
#      ldif: classpath:test-server.ldif
#      base-dn: dc=springframework,dc=org
#      port: 8389
#    urls: ldap://localhost:8389
#    base: ou=people,dc=springframework,dc=org
#    username: cn=admin,dc=baoban
#    password: anonymous